title: Libertis
description: Association des professionnels du logiciel libre Aix-Marseille

# disabled because we are using a custom domain
#baseurl: /business-frontpage 

color-scheme: "mediumseagreen" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
